### ISSUE TITLE
smoke_test.py issue

### ISSUE THREAD

**Issue by yeonjisong** [martius-lab/SMORL#3]
`python -W ignore ./rlkit/settings/smorl/smoke_test.py`

I am keep getting 'Attribute error' when running this test file.

**Comment by zadaianchuk** [comment]
@yeonjisong Can you provide more details / exact error message? 
I just checked that the tests are still passing for me using fresh conda env (I've added mujoco-py version in new .yml file for better reproduction)

**Comment by yeonjisong** [comment]
I think there is an issue with swig, while building Box2D
